version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.11"

exclude_patterns = [
  "tests/**",      # Skip tests if you don't want them analyzed
  "**/migrations/**",  # Common Django/ORM pattern to exclude
]

[[transformers]]
name = "autopep8"  # Optional, auto-formatting transformer

